---
- name: Add gpg key
  ansible.builtin.apt_key:
    url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
    state: present
- name: Add repository
  ansible.builtin.apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    filename: spotify
- name: Install package
  ansible.builtin.apt:
    name: spotify-client
    state: present