---
- name: Add vivaldis gpg key
  ansible.builtin.apt_key:
    url: https://packages.element.io/debian/element-io-archive-keyring.gpg
    state: present
- name: Add repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.element.io/debian/ default main
    state: present
    filename: vivaldi
- name: Install stable binary
  ansible.builtin.apt:
    name: element-desktop
    state: present
